### ISSUE TITLE
can't build OpenCvSharpExtern (dll/so) from opencvsharp 2.4.10-20170126 on arm

### ISSUE THREAD

**Issue by rblenis** [shimat/opencvsharp#400]
# Summary of your issue
I'm trying to build OpenCvSharpExtern dll(.so), so I can run my app on arm (nvidia tegra tk1).  

# Environment

ubuntu 14.04 on jetson (tk1), and ubuntu 17.10 on my laptop using chroot/arm emulator.

# What did you do when you faced the problem?

I followed the steps from https://github.com/shimat/opencvsharp/wiki/Tutorial-for-Ubuntu-14.04

specifically, I did:

mkdir test
cd test

sudo apt install libgtk2.0-dev libv4l-dev libavcodec-dev libavformat-dev libswscale-dev

wget http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.10/opencv-2.4.10.zip
unzip opencv-2.4.10.zip
cd opencv-2.4.10
mkdir build
cd build
cmake ..
make -j 4
sudo make install
cd ../..

git clone https://github.com/shimat/opencvsharp.git
cd opencvsharp
git checkout tags/2.4.10.20170126
mkdir build
cd build
cmake ../src
make -j 4
# I can't get past here!! make fails!
sudo make install
cd ../..

## Output:

[  4%] Building CXX object OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/features2d.cpp.o
In file included from /home/ubuntu/test/opencvsharp/src/OpenCvSharpExtern/features2d.h:4:0,
                 from /home/ubuntu/test/opencvsharp/src/OpenCvSharpExtern/features2d.cpp:1:
/home/ubuntu/test/opencvsharp/src/OpenCvSharpExtern/include_opencv.h:13:39: fatal error: opencv2/calib3d/calib3d_c.h: No such file or directory
 #include <opencv2/calib3d/calib3d_c.h>
                                       ^
compilation terminated.
make[2]: *** [OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/features2d.cpp.o] Error 1
make[1]: *** [OpenCvSharpExtern/CMakeFiles/OpenCvSharpExtern.dir/all] Error 2

```

## What did you intend to be?

I've tried editing the include files to use the only found calib3d header file (calib3d.hpp) but no joy :(

**Comment by DaEkstrim** [comment]
@rblenis I'm going to try to take a stab at this. I believe that the source you downloaded for opencvsharp from github targets OpenCV3.2. I don't know how backwards compatibility works with older versions of OpenCV. I managed to build on linux systems (particularly Raspbian, but should work for most distros). Take a look at my notes at https://github.com/shimat/opencvsharp/issues/388#issuecomment-337953321

**Comment by rblenis** [comment]
@DaEkstrim, Thanks.  I did get the a opencvsharp code from github, but 
then did checkout to the 2.4.10.20170126 tag, so hopefully that is 
actually the 2.4.10 compatible version.  If not, then where is the 
2.4.10 opencvsharp repo?  I'm actually using the nuget package 
2.4.10.20170306 in my application, but there wasn't a newer tag in the 
repo other than 3.x series.  I saw your comments on building 3.2 and was 
already planning on taking a look at it today.  I think I will have to 
make a lot of changes to my application to convert to opencv 3.2. Of 
course if that gets me past this problem, then I will do it. Wasn't 
planning on changing over to 3.2 for awhile, especially not just before 
planned customer release :(  Thanks for your help.

**Comment by DaEkstrim** [comment]
Huh.. where did my edited comment go?
@rblenis Apologies, I should have read the fine details that you're targeting Ubuntu 14.10, which limits the version of OpenCV. I'm throwing a wild guess here because I have no experience in the older version of opencvsharp, but your problem may be similar to the one I was having trouble with; i.e. finding headers for opencv in 3.2. In your CMakeList.txt did you add a line to include the `/usr/local/include` which contains openCv?

**Comment by rblenis** [comment]
I didn't make any changes to makefiles, etc., but the problem is, the 
include file it is looking for, calib3d_c.h, does not exist anywhere on 
my system, even though I downloaded the source for opencv, built it and 
installed it.  I don't mind building and using opencv 3.2, but I have a 
lot of code in my application that I will have to change to make use of 
opencvsharp 3.2

**Comment by DaEkstrim** [comment]
@rblenis I did some digging into to find where the file first appeared, and it seems that the particular file calib3dc_h, first appeared in OpenCV commit tag/3.0.0.

So then I looked into the commit history for include_opencv.h and it seems that, that paritcular include line was added in commit https://github.com/shimat/opencvsharp/commit/259a11a050d3813a34cbc60247c64c638ea9ee2d#diff-47f287d77c1740f7ec63e2eadf7abcd6 which happened on 29th August 2015

The latest tag for 2.4.10 without that commit was '2.4.10.20150820'. Hence my suggestion is: Can you check out that tag when fetching opencvsharp?

This took me quite a bit of time to dig into (with no previous experience what so ever), so apologies if this leads to nowhere.

**Comment by rblenis** [comment]
Thanks for your feedback.  I checked out the 3.2 version and was able to build the OpenCvSharpExtern dll with only one minor patch to prevent 3 or 4 errors compiling. A portion of the error output is below. I just had to add a space in the appropriate place on 3 or 4 lines as suggested by the gcc error message, and it built without any problem.  I'm in the middle of updating my application to use the 3.2 version, and will hopefully be done by tomorrow morning. I won't be able to use the full set of dlls  from version 20150820 though, because there are bugs in that version that cause memory corruption/crashes due to garbage collection that are not resolved until version 2.4.10-20151220. Maybe the OpenCvSharpExtern dll built from 20150820 will work with the newer 2.4.10 opencvsharp dlls. Will dig into more after I get the 3.2 support finished and tested.

------------ output snippet, compiling opencvsharp 3.2 ------------------

/opencvsharp/src/OpenCvSharpExtern/aruco.h:22:40: error: ‘>>’ should be ‘> >’ within a nested template argument list
     std::vector<std::vector<cv::Point2f>> cornerVec(cornerSize1);

-------------------------------------------

**Comment by DaEkstrim** [comment]
I understand. And I'm perplexed on how you encountered compilation errors with 3.2. I didn't have to change anything apart from `set (CMAKE_CXX_STANDARD 11)` in the CMakeList.txt. I'll be looking forward to hear if you managed to use the latest opencvsharp 2.4.10 with the 20151220 OpenCvSharpExtern if you get around to it.

**Comment by rblenis** [comment]
I didn't do any special config changes (like the CXX STANDARD change you did). By default, gcc 4.8 uses the c++98 standard, which will not disambiguate the '>>' as a template closure.  I could have re configured with forced the c++11 standard and rebuilt, but went for the quick fix.  I'll go back and re-fix the makefile the correct way to force c++11 and submit a patch, when I get a chance.

**Comment by rblenis** [comment]
looks like there has already been a fix for the compilation error I ran into with support for older compilers, which I hadn't noticed was already reported in as issue #395. I haven't looked into the 2.4.x issue any further since I have been able to upgrade our application to version 3.2.x.
